urls.py
from django.urls import path

from . import views

app_name = 'cal'

urlpatterns = [
    path('',views.loginfunc,name="top"),
    # path('signup/',signupfunc,name='signup'),
    path('login/',views.loginfunc),
    path('cal_list/', views.TOPListView.as_view(), name='cal_list'),
    path('item_list/', views.CalorieListView.as_view(), name='item_list'),
    path('day_create/', views.DayCreateView.as_view(), name='day_create'),
    path('calorie_create/', views.CalorieCreateView.as_view(), name='calorie_create'),
    path('create_done/',views.create_done, name='create_done'),
    # path('new_cal/',views.TOPView, name='new_cal'),
    path('update/<int:pk>',views.TOPUpdateView.as_view(),name='TOP_update'),
    path('update_done/', views.update_done, name='update_done'),
    path('delete/<int:pk>/',views.TOPDeleteView.as_view(),name='TOP_delete'),
    path('delete_done',views.delete_done,name='delete_done')
    ]

models.py
from django.db import models
from datetime import datetime 
from django.db.models import Avg,Sum



class Choice(models.Model):
    name = models.CharField(max_length=255,unique=True)

    def __str__(self):
        return self.name


class Calorie(models.Model):
    class Meta:
        db_table="Calorie"
        verbose_name="商品管理"
        verbose_name_plural="商品管理"

    name=models.CharField(verbose_name="商品名",max_length=50,unique=True)
    category = models.ForeignKey(Choice, on_delete = models.PROTECT, verbose_name="ジャンル")
    cal=models.IntegerField(verbose_name="カロリー",help_text="単位はkcal(半角数字のみ可)")

    # def cals(self):
    #     Calorie.objects.all().aggregate(Avg('cal'))


    def __str__(self):
        return self.name
        # return Calorie.objects.all().count()



class TOP(models.Model):
    class Meta:
        db_table="TOP"
        verbose_name="データ"
        # verbose_name_plural="トップ表示"

    date=models.DateField(verbose_name="日付",default=datetime.now,unique=True)
    total_cal=models.ManyToManyField(Calorie, related_name='計カロリー',verbose_name="飲食したもの")
    
    def __str__(self):
        return str(self.date)
    # def cals(self):
    #     return "\n".join([p.total_cal for p in self.total_cal.all()])
    
    # def cals(self):
    #     return total_cal.objects.all().count()
    # def __str__(self):
    #     return str(self.date)

forms.py
from django import forms
from .models import Calorie,TOP

class CalorieForm(forms.ModelForm):
    class Meta:
     model=Calorie
     fields=['name','category','cal']


class TOPForm(forms.ModelForm):
    class Meta:
     model=TOP
     fields=['date','total_cal']

views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView, ListView, UpdateView, DeleteView,TemplateView
from .models import Choice,Calorie,TOP
from django.urls import reverse_lazy
from . forms import CalorieForm,TOPForm
from django.contrib.auth import authenticate, login
# Create your views here.
# class Top(TemplateView):
#     template_name = "cal/index.html"

class TOPListView(ListView):
    model=TOP
    template_name='cal/cal_list.html'

class CalorieListView(ListView):
    model=Calorie
    template_name='cal/item_list.html'

class DayCreateView(CreateView):
    model=TOP
    form_class=TOPForm
    success_url = reverse_lazy('cal:create_done')

class CalorieCreateView(CreateView):
    model=Calorie
    form_class=CalorieForm
    success_url = reverse_lazy('cal:create_done')


class TOPUpdateView(UpdateView):
    model=TOP
    form_class=TOPForm
    success_url=reverse_lazy('cal:update_done')

def update_done(request):
    return render(request, 'cal/update_done.html')

def create_done(request):
    return render(request,'cal/create_done.html')

class TOPDeleteView(DeleteView):
    model=TOP
    success_url = reverse_lazy('cal:delete_done')

def delete_done(request):
    return render(request, 'cal/delete_done.html')

def loginfunc(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
           login(request, user)
           return render(request,'cal/cal_list.html')
        else:
           return render(request,'cal/index.html',{'error':'IDまたはpasswordが正しくありません。'})
    return render(request,'cal/index.html')

templates/cal/TOP_confirm_delete.html
{% extends 'cal/base.html' %}
{% block content %}
<div class="content-wrapper">
  <div class="container-fluid">
    <div class="card mb-3">
      <div class="card-header">
        <h3>データ削除</h3>
      </div>
    </div>
    <div class="content-wrapper">
      <div class="container-fluid">
        <p>{{ object }} のデータを削除していいですか?</p>
        <form method="post">
          <button class="btn btn-danger">削除する</button>
          {% csrf_token %}
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/cal/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static 'calorie.css'%}">
  <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@500&display=swap" rel="stylesheet">
  <link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:wght@700&family=Oswald:wght@500&display=swap"
    rel="stylesheet">
  <link
    href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@100;300;500&family=Noto+Sans+JP:wght@500&family=Noto+Serif+JP:wght@200&display=swap"
    rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
  {% comment %}
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> {% endcomment %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.css" />
  <title>Calorie Life</title>
</head>

<body>
  {% block content %}
  {% endblock %}
  <footer class="footer">Copyright © 2020 CalorieLife Inc. All Rights Reserved. </footer>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

  <script src="https://cdn.datatables.net/t/bs-3.3.6/jqc-1.12.0,dt-1.10.11/datatables.min.js"></script>
  <script>
    jQuery(function ($) {
      $.extend($.fn.dataTable.defaults, {
        language: {
          url: "http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Japanese.json"
        }
      });
      $("#cal_list").DataTable({
      }).columns.adjust();
    });  
  </script>
</body>

</html>

templates/cal/cal_list.html
{% extends 'cal/base.html' %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="nav">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:top' %}">トップに戻る</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:day_create' %}">記録をつける</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">食事記録<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:calorie_create' %}">食品を追加する</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'cal:item_list' %}" tabindex="-1" aria-disabled="true">カロリー表はこちら！！</a>
      </li>
    </ul>
  </div>
</nav>
<div class="content-wrapper">
  <div class="container-fluid">


    <ol class="breadcrumb" id="bread">
      <li><a href="{% url 'cal:top' %}">トップに戻る</a></li>
      <li><a href="{% url 'cal:day_create' %}">記録をつける</a></li>
      <li class="breadcrumb-item">食事記録</li>
      <li><a href="{% url 'cal:calorie_create' %}">食品を追加する</a></li>
      <li><a href="{% url 'cal:item_list' %}">カロリー表はこちら！！</a></li>
    </ol>

    <div class="head mb-3">
      <div class="card-head ">
        <div class="toumei">
          <h3>食事記録</h3>
        </div>
      </div>
      <div class="card-body">

        <div class="table-responsive">
          <table id=cal_list width="100%" class="table table-striped table-bordered table-hover">


            <thead>
              <tr class="success">
                <th class="text-center">日付</th>
                <th class="text-center">食べたもの</th>
                <th class="text-center">変更・削除</th>

                {% comment %} <th class="text-center">金額</th> {% endcomment %}
                {% comment %} <th class="text-center">メモ</th> {% endcomment %}
              </tr>
            </thead>

            <tbody>
              {% for item in object_list %}
              <tr class=" odd gradeX text-center">
                <td class="text-center" width="1">{{ item.date}}</td>
                <td class="text-center" width="150">{% for i in item.total_cal.all %}
                  {{ i }}
                  {% endfor%}</td>
                <td class="text-center" width="1"><a class="btn btn-primary"
                    href="{% url 'cal:TOP_update' item.pk %}">変更</a>


                  　
                  <a class="btn btn-danger" href="{% url 'cal:TOP_delete' item.pk %}">削除</a>
                </td>
                {% comment %} <td class="text-center" width="140">{{ item.cal }}</td> {% endcomment %}
                {% comment %} <td class="text-center" width="140">{{ item.memo }}</td> {% endcomment %}
              </tr>
              {% endfor %}
            </tbody>

          </table>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/cal/calorie_form.html
{% extends 'cal/base.html' %}
{% load bootstrap %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="nav">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:top' %}">トップに戻る</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:day_create' %}">記録をつける</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:cal_list' %}">食事記録</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">食品を追加する<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'cal:item_list' %}" tabindex="-1" aria-disabled="true">カロリー表はこちら！！</a>
      </li>
    </ul>
  </div>
</nav>

<form method="post">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="content-wrapper">
          <div class="container-fluid">
            <ol class="breadcrumb" id="bread">
              <li><a href="{% url 'cal:top' %}">トップに戻る</a></li>
              <li><a href="{% url 'cal:day_create' %}">記録をつける</a></li>
              <li class="breadcrumb-item">
                <a href="{% url 'cal:cal_list' %}">食事記録</a>
              </li>
              <li>食品を追加する</li>
              <li><a href="{% url 'cal:item_list' %}">カロリー表はこちら！！</a></li>
            </ol>
            <div class="card mb-3">
              <div class="card-header">
                <i class="fa fa-server"></i>
                <h3>食品登録画面</h3>
                <h5 class="text-danger">一度登録した食品は管理者以外変更・削除できないのでご注意を！</h5>
              </div>
              <div class="card-body"> {{ form|bootstrap }}
              </div>
            </div>
            <div class="row">
              <div class="col-12">
                <button class="btn btn-primary">保存</button>
              </div>
            </div>
          </div>
          {% csrf_token %}
</form>
{% endblock %}

templates/cal/create_done.html
{% extends 'cal/base.html' %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="nav">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:top' %}">トップに戻る</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:day_create' %}">記録をつける</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:cal_list' %}">食事記録</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:calorie_create' %}">食品を追加する</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'cal:item_list' %}" tabindex="-1" aria-disabled="true">カロリー表はこちら！！</a>
      </li>
    </ul>
  </div>
</nav>

<div class="content-wrapper">
  <div class="container-fluid">

    <ol class="breadcrumb" id="bread">
      <li><a href="{% url 'cal:top' %}">トップに戻る</a></li>
      <li><a href="{% url 'cal:day_create' %}">記録をつける</a></li>
      <li class="breadcrumb-item">
        <a href="{% url 'cal:cal_list' %}">食事記録</a>
      </li>
      <li><a href="{% url 'cal:calorie_create' %}">食品を追加する</a></li>
      <li><a href="{% url 'cal:item_list' %}">カロリー表はこちら！！</a></li>
    </ol>

    <div class="card mb-3">

      <div class="card-body">
        <div class="alert alert-info" role="alert">データ登録が正常終了しました。</div>
        {% endblock content %}

templates/cal/delete_done.html
{% extends 'cal/base.html' %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="nav">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:top' %}">トップに戻る</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:day_create' %}">記録をつける</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:cal_list' %}">食事記録</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:calorie_create' %}">食品を追加する</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'cal:item_list' %}" tabindex="-1" aria-disabled="true">カロリー表はこちら！！</a>
      </li>
    </ul>
  </div>
</nav>

<div class="content-wrapper">
  <div class="container-fluid">

    <ol class="breadcrumb" id="bread">
      <li><a href="{% url 'cal:top' %}">トップに戻る</a></li>
      <li><a href="{% url 'cal:day_create' %}">記録をつける</a></li>
      <li class="breadcrumb-item">
        <a href="{% url 'cal:cal_list' %}">食事記録</a>
      </li>
      <li><a href="{% url 'cal:calorie_create' %}">食品を追加する</a></li>
      <li><a href="{% url 'cal:item_list' %}">カロリー表はこちら！！</a></li>
    </ol>

    <div class="card mb-3">

      <div class="card-body">
        <div class="alert alert-info" role="alert">データの解除が正常終了しました。</div>
        {% endblock content %}

templates/cal/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <link rel="stylesheet" href="{% static 'style.css'%}">
  <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@500&display=swap" rel="stylesheet">
  <link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:wght@700&family=Oswald:wght@500&display=swap"
    rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">
</head>

<body>
  <div class="wrapper">
    <div class="w2">
      <h1>Calorie Life</h1>

      {%if error%}
      {{error}}
      {%endif%}
      <form class="form-signin" method="POST" action=''>{% csrf_token %}

        <h6 for="inputEmail" class="sr-only">ID</h6>
        <input type="text" id="inputEmail" class="form-control" name='username' placeholder="username" required
          autofocus>

        <h6 for="inputPassword" class="sr-only">Password</h6>
        <input type="password" id="inputPassword" class="form-control" name='password' placeholder="Password" required>
        <div class="checkbox mb-3">
        </div>
        <button class="btn" type="submit">はじめる</button>

      </form>
      <h2>このサイトでできること</h2>
      <h3>①日々の食事記録を残せる！</h3>
      <p>食品リストから食べたものを選択するだけで簡単に日々の食事管理ができます。</p>
      <h3>②食品のカロリー一覧を見れる！</h3>
      <p>カロリー情報つきの食品リストがいつでも見れるので、自分の料理の参考や、健康管理に使用できます。</p>
      <p>一覧にない食品や自分オリジナルのメニューはワンクリックで簡単に登録できます！</p>


      <p class="footer">Copyright © 2020 Calorie Life Inc. All Rights Reserved. </pr>
    </div>
  </div>
</body>
<script type="text/javascript" src="{% static 'js.js'%}"></script>

</html>

templates/cal/item_list.html
{% extends 'cal/base.html' %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="nav">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:top' %}">トップに戻る</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:day_create' %}">記録をつける</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:cal_list' %}">食事記録</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:calorie_create' %}">食品を追加する</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">カロリー表はこちら！！<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>

<div class="content-wrapper">
  <div class="container-fluid">
    <ol class="breadcrumb" id="bread">
      <li><a href="{% url 'cal:top' %}">トップに戻る</a></li>
      <li><a href="{% url 'cal:day_create' %}">記録をつける</a></li>
      <li class="breadcrumb-item">
        <a href="{% url 'cal:cal_list' %}">食事記録</a>
      </li>
      <li><a href="{% url 'cal:calorie_create' %}">食品を追加する</a></li>
      <li>カロリー表はこちら！！</li>
    </ol>

    <div class="head ">
      <div class="card-head2">
        <div class="toumei">
          <h3><b>カロリー表</b></h3>
        </div>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table id="cal_list" width="100%" class="table table-striped table-bordered table-hover">
            <thead>
              <tr class="info">
                <th class="text-center">商品</th>
                <th class="text-center">ジャンル</th>
                <th class="text-center">カロリー</th>
              </tr>
            </thead>
            <tbody>
              {% for item in object_list %}
              <tr class="odd gradeX text-center">
                <td class="text-center" width="100">{{ item.name}}</td>
                <td class="text-center" width="100">{{ item.category }}</td>
                <td class="text-center" width="140">{{ item.cal }}</td>

              </tr>
              {% endfor %}
            </tbody>
          </table>
          <h5 class="text-info">表に無い食品はお手数ですが上記「食品を追加する」より追加してください。</h5>
          <h5 class="text-danger">表記の文字や値が明らかにおかしいと感じたものは変更・削除を行う可能性がございます。</h5>
        </div>

      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/cal/top_form.html
{% extends 'cal/base.html' %}
{% load bootstrap %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="nav">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
          <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:top' %}">トップに戻る</a>
      </li>
      <li class="nav-item">
        <a ></a>記録をつける</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:cal_list' %}">食事記録</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:calorie_create' %}">食品を追加する</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'cal:item_list' %}" tabindex="-1" aria-disabled="true">カロリー表はこちら！！</a>
      </li>
    </ul>
  </div>
</nav>

<form method="post">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="content-wrapper">
          <div class="container-fluid">

            <ol class="breadcrumb" id="bread">
              <li><a href="{% url 'cal:top' %}">トップに戻る</a></li>
              <li><a href="{% url 'cal:day_create' %}"></a>記録をつける</a></li>
              <li class="breadcrumb-item">
                <a href="{% url 'cal:cal_list' %}">食事記録</a>
              </li>
              <li><a href="{% url 'cal:calorie_create' %}">食品を追加する</a></li>
              <li><a href="{% url 'cal:item_list' %}">カロリー表はこちら！！</a></li>
            </ol>

            <div class="card mb-3">
              <div class="card-header">
                <i class="fa fa-server"></i>
                <h3>食事記録</h3>
              </div>
              <div class="card-body"> {{ form|bootstrap }}
              </div>
            </div>
            <div class="row">
              <div class="col-12">
                <button class="btn btn-primary">保存</button>
              </div>
            </div>
          </div>
          {% csrf_token %}
</form>
{% endblock %}

templates/cal/update_done.html
{% extends 'cal/base.html' %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light" id="nav">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:top' %}">トップに戻る</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:day_create' %}">記録をつける</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:cal_list' %}">食事記録</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cal:calorie_create' %}">食品を追加する</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% url 'cal:item_list' %}" tabindex="-1" aria-disabled="true">カロリー表はこちら！！</a>
      </li>
    </ul>
  </div>
</nav>


<div class="content-wrapper">
  <div class="container-fluid">
    <ol class="breadcrumb" id="bread">
      <li><a href="{% url 'cal:top' %}">トップに戻る</a></li>
       <li><a href="{% url 'cal:day_create' %}">記録をつける</a></li>
      <li class="breadcrumb-item">
        <a href="{% url 'cal:cal_list' %}">食事記録</a>
      </li>
      <li><a href="{% url 'cal:calorie_create' %}">食品を追加する</a></li>
      <li><a href="{% url 'cal:item_list' %}">カロリー表はこちら！！</a></li>
    </ol>
    <div class="card mb-3">
      <div class="card-body">
        <div class="alert alert-info" role="alert">データ更新が正常終了しました。</div>
        {% endblock content %}